# Generated by Django 4.2.16 on 2024-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profiles", name="status",),
        migrations.AddField(
            model_name="profiles",
            name="department",
            field=models.CharField(
                choices=[
                    ("Accounting/Finance", "Accounting/Finance"),
                    ("Customer Service", "Customer Service"),
                    ("Human Resources", "Human Resources"),
                    ("Information Technology", "Information Technology"),
                    ("Investment Banking & Market", "Investment Banking & Market"),
                ],
                max_length=60,
                null=True,
            ),
        ),
    ]
