# Generated by Django 4.2.16 on 2024-10-13 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account_table",
            fields=[
                ("account_id", models.AutoField(primary_key=True, serialize=False)),
                ("account_balance", models.BigIntegerField(default=0)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Savings", "Savings"),
                            ("Current", "Current"),
                            ("Fixed Deposit", " Fixed Deposit"),
                            ("Domicilliary", "Domicilliary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(default="2234257117", max_length=10, unique=True),
                ),
                ("account_pin", models.IntegerField(default=0)),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Retired", "Retired"),
                            ("Suspended", "Suspended"),
                            ("Freeze", "Freeze"),
                            ("On Leave", "On Leave"),
                            ("Dormant", "Dormant"),
                        ],
                        default="Active",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
