# Generated by Django 4.2.16 on 2024-11-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactionapp", "0002_alter_account_table_account_number_transaction_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction_table",
            name="beneficiary_account_number",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="transaction_table",
            name="beneficiary_bank",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="account_table",
            name="account_number",
            field=models.CharField(default="2227234126", max_length=10, unique=True),
        ),
    ]
